vich_uploader:
    db_driver: orm
    
   #PHP 8 ONLY 
    metadata:
        type: attribute

    mappings:
       livres:
           uri_prefix: /images/livres
           upload_destination: '%kernel.project_dir%/public/images/livres'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
